name: Push Gem to RubyGems.org

on:
  push:
    tags: ['v*']

permissions:
  contents: read

jobs:
  push:
    name: Push Gem to RubyGems.org
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      # Set up
      - name: Checkout
        uses: actions/checkout@v4
      # Setup Ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      # Release
      - uses: rubygems/release-gem@v1